fix: cannot find remote branch
githubocto/repo-visualizer pull request #49
Opened 2022-08-20 11:02 UTC by alichherawalla

Hi, 

Thank you for this amazing library! In terms of getting a fingerprint of the project and its structure, there is nothing that I have come across that is easier to use. 

While running this action in one of my repos I faced the following issue which this PR resolves

```
/usr/bin/git rev-parse --verify <branch-name>
fatal: Needed a single revision
```

and there after pushing fails since it tries to push to a branch that already exists

```
  /usr/bin/git push --set-upstream origin <branch-name>
  To https://github.com/<org>/<repo-name>
   ! [rejected]        visualizer -> visualizer (non-fast-forward)
  error: failed to push some refs to 'https://github.com/<org>/<repo-name>'
  hint: Updates were rejected because the tip of your current branch is behind
  hint: its remote counterpart. Integrate the remote changes (e.g.
  hint: 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Changing to git switch with the --track flag solves the problem.

2022-08-20 11:03 UTC, alichherawalla commented
This PR addresses and solves [this](https://github.com/githubocto/repo-visualizer/issues/42) issue

2022-08-20 11:04 UTC, alichherawalla commented
@Wattenberger  If possible please take a look at this PR

2022-09-09 09:52 UTC, alichherawalla commented
possible to please get a review here?

2022-09-13 16:31 UTC, Wattenberger commented on index.js
> +  const commitMessage = core.getInput("commit_message") || "Repo visualizer: update diagram";
you'll want to make this change in src/index.jsx:30

2022-09-13 16:33 UTC, Wattenberger requested changes
this is great, thanks for the PR! sorry about the delay, we've been focusing on other projects at the moment. If you want to move the commit message name change to the uncompiled file, I can merge after!

2022-09-13 16:37 UTC, Wattenberger approved these changes
ah, I see! that's from a previous change - we're all good!

2022-09-13 16:37 UTC, merged